# Generated by Django 2.1 on 2018-08-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spauser',
            name='money',
            field=models.FloatField(default=0.0),
        ),
    ]
