# Generated by Django 2.1 on 2018-08-20 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_spauser_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spauser',
            name='money',
        ),
    ]
