# Generated by Django 2.1 on 2018-08-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monedaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerow',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='monedaapp.Exchange'),
        ),
    ]
